// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hruluaomdkvwhobrpwlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydWx1YW9tZGt2d2hvYnJwd2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzc3NzAsImV4cCI6MjA2MzgxMzc3MH0.gque--r0S4-typp0WMXtPjPciJydRpTS6VdbTcWYfTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);